######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 24 20:36:02 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
