######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 8 15:58:18 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
